# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt-get install -y libgtk-3-dev libjpeg-dev dpkg-dev devscripts
      - run: go get -v -t -d ./...
      - run: gotestsum --junitfile unit-tests.xml
      - store_test_results:
          path: .
      - run: ./script/build-linux.sh
      - run: ./script/package-linux.sh
      - store_artifacts:
          path: deploy/linux/artifacts
