package common

import (
	"github.com/go-gl/glfw/v3.3/glfw"
)

/*
These have to stay under common since
* UI uses them to convert between UI <-> Human
* Backend uses to convert between Serialized <-> UI
*/

var keymapStringToKey = map[string]glfw.Key{
	"Space":         glfw.KeySpace,
	"'":             glfw.KeyApostrophe,
	",":             glfw.KeyComma,
	"-":             glfw.KeyMinus,
	".":             glfw.KeyPeriod,
	"/":             glfw.KeySlash,
	"0":             glfw.Key0,
	"1":             glfw.Key1,
	"2":             glfw.Key2,
	"3":             glfw.Key3,
	"4":             glfw.Key4,
	"5":             glfw.Key5,
	"6":             glfw.Key6,
	"7":             glfw.Key7,
	"8":             glfw.Key8,
	"9":             glfw.Key9,
	":":             glfw.KeySemicolon,
	"=":             glfw.KeyEqual,
	"A":             glfw.KeyA,
	"B":             glfw.KeyB,
	"C":             glfw.KeyC,
	"D":             glfw.KeyD,
	"E":             glfw.KeyE,
	"F":             glfw.KeyF,
	"G":             glfw.KeyG,
	"H":             glfw.KeyH,
	"I":             glfw.KeyI,
	"J":             glfw.KeyJ,
	"K":             glfw.KeyK,
	"L":             glfw.KeyL,
	"M":             glfw.KeyM,
	"N":             glfw.KeyN,
	"O":             glfw.KeyO,
	"P":             glfw.KeyP,
	"Q":             glfw.KeyQ,
	"R":             glfw.KeyR,
	"S":             glfw.KeyS,
	"T":             glfw.KeyT,
	"U":             glfw.KeyU,
	"V":             glfw.KeyV,
	"W":             glfw.KeyW,
	"X":             glfw.KeyX,
	"Y":             glfw.KeyY,
	"Z":             glfw.KeyZ,
	"[":             glfw.KeyLeftBracket,
	"\\":            glfw.KeyBackslash,
	"]":             glfw.KeyRightBracket,
	"`":             glfw.KeyGraveAccent,
	"ESC":           glfw.KeyEscape,
	"Enter":         glfw.KeyEnter,
	"Tab":           glfw.KeyTab,
	"Backspace":     glfw.KeyBackspace,
	"Insert":        glfw.KeyInsert,
	"Delete":        glfw.KeyDelete,
	"Right":         glfw.KeyRight,
	"Left":          glfw.KeyLeft,
	"Down":          glfw.KeyDown,
	"Up":            glfw.KeyUp,
	"PageUp":        glfw.KeyPageUp,
	"PageDown":      glfw.KeyPageDown,
	"Home":          glfw.KeyHome,
	"End":           glfw.KeyEnd,
	"Caps Lock":     glfw.KeyCapsLock,
	"Scroll Lock":   glfw.KeyScrollLock,
	"Num Lock":      glfw.KeyNumLock,
	"Print Screen":  glfw.KeyPrintScreen,
	"Pause":         glfw.KeyPause,
	"F1":            glfw.KeyF1,
	"F2":            glfw.KeyF2,
	"F3":            glfw.KeyF3,
	"F4":            glfw.KeyF4,
	"F5":            glfw.KeyF5,
	"F6":            glfw.KeyF6,
	"F7":            glfw.KeyF7,
	"F8":            glfw.KeyF8,
	"F9":            glfw.KeyF9,
	"F10":           glfw.KeyF10,
	"F11":           glfw.KeyF11,
	"F12":           glfw.KeyF12,
	"F13":           glfw.KeyF13,
	"F14":           glfw.KeyF14,
	"F15":           glfw.KeyF15,
	"F16":           glfw.KeyF16,
	"F17":           glfw.KeyF17,
	"F18":           glfw.KeyF18,
	"F19":           glfw.KeyF19,
	"F20":           glfw.KeyF20,
	"F21":           glfw.KeyF21,
	"F22":           glfw.KeyF22,
	"F23":           glfw.KeyF23,
	"F24":           glfw.KeyF24,
	"F25":           glfw.KeyF25,
	"Key Pad 0":     glfw.KeyKP0,
	"Key Pad 1":     glfw.KeyKP1,
	"Key Pad 2":     glfw.KeyKP2,
	"Key Pad 3":     glfw.KeyKP3,
	"Key Pad 4":     glfw.KeyKP4,
	"Key Pad 5":     glfw.KeyKP5,
	"Key Pad 6":     glfw.KeyKP6,
	"Key Pad 7":     glfw.KeyKP7,
	"Key Pad 8":     glfw.KeyKP8,
	"Key Pad 9":     glfw.KeyKP9,
	"Key Pad ,":     glfw.KeyKPDecimal,
	"Key Pad /":     glfw.KeyKPDivide,
	"Key Pad *":     glfw.KeyKPMultiply,
	"Key Pad -":     glfw.KeyKPSubtract,
	"Key Pad +":     glfw.KeyKPAdd,
	"Key Pad Enter": glfw.KeyKPEnter,
	"Key Pad =":     glfw.KeyKPEqual,
	"Left Shift":    glfw.KeyLeftShift,
	"Left Control":  glfw.KeyLeftControl,
	"Left Alt":      glfw.KeyLeftAlt,
	"Left Super":    glfw.KeyLeftSuper,
	"Right Shift":   glfw.KeyRightShift,
	"Right Control": glfw.KeyRightControl,
	"Right Alt":     glfw.KeyRightAlt,
	"Right Super":   glfw.KeyRightSuper,
	"Menu":          glfw.KeyMenu,
}
var keymapKeyToString = map[glfw.Key]string{
	glfw.KeySpace:        "Space",
	glfw.KeyApostrophe:   "'",
	glfw.KeyComma:        ",",
	glfw.KeyMinus:        "-",
	glfw.KeyPeriod:       ".",
	glfw.KeySlash:        "/",
	glfw.Key0:            "0",
	glfw.Key1:            "1",
	glfw.Key2:            "2",
	glfw.Key3:            "3",
	glfw.Key4:            "4",
	glfw.Key5:            "5",
	glfw.Key6:            "6",
	glfw.Key7:            "7",
	glfw.Key8:            "8",
	glfw.Key9:            "9",
	glfw.KeySemicolon:    ":",
	glfw.KeyEqual:        "=",
	glfw.KeyA:            "A",
	glfw.KeyB:            "B",
	glfw.KeyC:            "C",
	glfw.KeyD:            "D",
	glfw.KeyE:            "E",
	glfw.KeyF:            "F",
	glfw.KeyG:            "G",
	glfw.KeyH:            "H",
	glfw.KeyI:            "I",
	glfw.KeyJ:            "J",
	glfw.KeyK:            "K",
	glfw.KeyL:            "L",
	glfw.KeyM:            "M",
	glfw.KeyN:            "N",
	glfw.KeyO:            "O",
	glfw.KeyP:            "P",
	glfw.KeyQ:            "Q",
	glfw.KeyR:            "R",
	glfw.KeyS:            "S",
	glfw.KeyT:            "T",
	glfw.KeyU:            "U",
	glfw.KeyV:            "V",
	glfw.KeyW:            "W",
	glfw.KeyX:            "X",
	glfw.KeyY:            "Y",
	glfw.KeyZ:            "Z",
	glfw.KeyLeftBracket:  "[",
	glfw.KeyBackslash:    "\\",
	glfw.KeyRightBracket: "]",
	glfw.KeyGraveAccent:  "`",
	glfw.KeyEscape:       "ESC",
	glfw.KeyEnter:        "Enter",
	glfw.KeyTab:          "Tab",
	glfw.KeyBackspace:    "Backspace",
	glfw.KeyInsert:       "Insert",
	glfw.KeyDelete:       "Delete",
	glfw.KeyRight:        "Right",
	glfw.KeyLeft:         "Left",
	glfw.KeyDown:         "Down",
	glfw.KeyUp:           "Up",
	glfw.KeyPageUp:       "PageUp",
	glfw.KeyPageDown:     "PageDown",
	glfw.KeyHome:         "Home",
	glfw.KeyEnd:          "End",
	glfw.KeyCapsLock:     "Caps Lock",
	glfw.KeyScrollLock:   "Scroll Lock",
	glfw.KeyNumLock:      "Num Lock",
	glfw.KeyPrintScreen:  "Print Screen",
	glfw.KeyPause:        "Pause",
	glfw.KeyF1:           "F1",
	glfw.KeyF2:           "F2",
	glfw.KeyF3:           "F3",
	glfw.KeyF4:           "F4",
	glfw.KeyF5:           "F5",
	glfw.KeyF6:           "F6",
	glfw.KeyF7:           "F7",
	glfw.KeyF8:           "F8",
	glfw.KeyF9:           "F9",
	glfw.KeyF10:          "F10",
	glfw.KeyF11:          "F11",
	glfw.KeyF12:          "F12",
	glfw.KeyF13:          "F13",
	glfw.KeyF14:          "F14",
	glfw.KeyF15:          "F15",
	glfw.KeyF16:          "F16",
	glfw.KeyF17:          "F17",
	glfw.KeyF18:          "F18",
	glfw.KeyF19:          "F19",
	glfw.KeyF20:          "F20",
	glfw.KeyF21:          "F21",
	glfw.KeyF22:          "F22",
	glfw.KeyF23:          "F23",
	glfw.KeyF24:          "F24",
	glfw.KeyF25:          "F25",
	glfw.KeyKP0:          "Key Pad 0",
	glfw.KeyKP1:          "Key Pad 1",
	glfw.KeyKP2:          "Key Pad 2",
	glfw.KeyKP3:          "Key Pad 3",
	glfw.KeyKP4:          "Key Pad 4",
	glfw.KeyKP5:          "Key Pad 5",
	glfw.KeyKP6:          "Key Pad 6",
	glfw.KeyKP7:          "Key Pad 7",
	glfw.KeyKP8:          "Key Pad 8",
	glfw.KeyKP9:          "Key Pad 9",
	glfw.KeyKPDecimal:    "Key Pad ,",
	glfw.KeyKPDivide:     "Key Pad /",
	glfw.KeyKPMultiply:   "Key Pad *",
	glfw.KeyKPSubtract:   "Key Pad -",
	glfw.KeyKPAdd:        "Key Pad +",
	glfw.KeyKPEnter:      "Key Pad Enter",
	glfw.KeyKPEqual:      "Key Pad =",
	glfw.KeyLeftShift:    "Left Shift",
	glfw.KeyLeftControl:  "Left Control",
	glfw.KeyLeftAlt:      "Left Alt",
	glfw.KeyLeftSuper:    "Left Super",
	glfw.KeyRightShift:   "Right Shift",
	glfw.KeyRightControl: "Right Control",
	glfw.KeyRightAlt:     "Right Alt",
	glfw.KeyRightSuper:   "Right Super",
	glfw.KeyMenu:         "Menu",
}

func KeyvalName(keyval uint) string {
	return keymapKeyToString[glfw.Key(keyval)]
}

func KeyToUint(key string) uint {
	return uint(keymapStringToKey[key])
}
